### ISSUE TITLE
Duplicate Dialogue for Planet Description

### ISSUE THREAD

**Issue by johnny2trayz** [EDCD/EDDI#2633]
## What's Wrong
Duplicate Dialogue for Planet Description

### Expected
One description per planet. I understand there is a seperate description for after mapping, but there seems to be a third one that is the same as the first. It is not always an exact duplicate, but it does seem there is a second unnecessary call being done.

### Observed
Planet 3 is a notable Water world with terraformable conditions and abundant liquid water.
Mapping is now complete. Efficiency bonus awarded.  Planet 3 is a medium-gravity terraformable Water world.
Planet 3 is a notable Water world with potential for terraforming and abundant liquid water.

Planet A 4 is notable, with potential for terraforming.
Mapping is now complete. Efficiency bonus granted.  Planet A 4 is a low-gravity terraformable High metal content world.
Planet A 4 is notable, with terraformable conditions.

### Steps to reproduce
Scanning worlds.

### Configuration
* Version:  18.07
  * EDDI Version: 4.0.4
  * VoiceAttack Version: N/A
* Localization
  * EDDI's language: English
  * Voice: IVONA 2 Nicole

### Investigation Notes
None

### EDDI Logs
https://pastebin.com/fpseS30V
### Player journals
https://pastebin.com/qzHaJa7S

**Comment by Tkael** [comment]
Are you using the default personality?
If not, does the problem still occur after you switch to the default personality?
o7

**Comment by johnny2trayz** [comment]
I've edited the default personality because of past issues and do not know how to restore it.

**Comment by Tkael** [comment]
First, is the `Body mapped` script edited? If so, can you share the contents of that script?

![image](https://github.com/user-attachments/assets/818bf1f2-d4fc-4224-8e05-00daa49f0413)
You should be able to switch to the default personality from the `Active personality` dropdown on the Speech Responder tab.

**Comment by johnny2trayz** [comment]
It is set to default.

{_ Preferences _}

{set bodyReport to 2}             {_ 0 = No body report, 1 = Summary body report, 2 = Body report _}
{set recommendOtherMapping to 1}  {_ 0 or 1. If 1, recommends other bodies from the `Bodies to map` script _}

{_ Context}
{SetState('eddi_context_last_action', 'scan')}
{SetState('eddi_context_last_subject', 'body')}
{SetState('eddi_context_body_system', system.name)}
{SetState('eddi_context_body_name', event.name)}
{SetState('eddi_context_last_scan_estimated_value', event.estimatedvalue)}

{_ Process the event _}

{if ship.Role.edname = "Exploration" || ship.Role.edname = "Multipurpose":

    {Pause(3000)}

    {OneOf("Mapping", "{Occasionally(2, \"Surface\")} Map")}
    {OneOf("is", "is now")}
    {OneOf("complete", "finished")}.

    {if event.probesused <= event.efficiencytarget:
        Efficiency bonus {OneOf("awarded", "granted")}.
    }

    {Pause(500)}
    {if bodyReport = 2:
        {F("Body report")}
    |elif bodyReport = 1:
        {F("Body report summary")}
    }

    {if recommendOtherMapping: 
        {Pause(1500)}
        {F("Bodies to map")}
    }
}

**Comment by Tkael** [comment]
Ok. Please confirm if the issue repeats with the default personality?

**Comment by johnny2trayz** [comment]
Correct. All default now. No other personalities.

**Comment by Tkael** [comment]
Hi there. Please confirm if this resolved by swapping to the default personality? o7

**Comment by johnny2trayz** [comment]
The issue does not resolve when using default personality, same issue

**Comment by Tkael** [comment]
I think I found the issue. Please look to the next release for the fix.
